In [111]:
class LogisticRegression(object):
    """
    ------------
    eta : tham số học
    n_iter :số bước lặp
    -----------
    w_ : trọng số sau huấn luyện
      
    cost_ : hàm mất mát sau các bước lặp
    """
    def __init__(self, eta=0.01, n_iter=50):
        self.eta = eta
        self.n_iter = n_iter

    def fit(self, X, y):
        """ Huấn luyện
        X : n mẫu và n đặc trưng
        y : n nhãn

        """
        self.w_ = np.zeros(1 + X.shape[1])
        self.cost_ = []       
        for i in range(self.n_iter):
            y_val = self.activation(X)
            errors = (y - y_val)
            neg_grad = X.T.dot(errors)
            self.w_[1:] += self.eta * neg_grad
            self.w_[0] += self.eta * errors.sum()
            self.cost_.append(self._logit_cost(y, self.activation(X)))
        return self

    def _logit_cost(self, y, y_val):
        logit = -y.dot(np.log(y_val)) - ((1 - y).dot(np.log(1 - y_val)))
        return logit
    
    def _sigmoid(self, z):
        return 1.0 / (1.0 + np.exp(-z))
    
    def net_input(self, X):
        """tổ hợp tuyến tính"""
        return np.dot(X, self.w_[1:]) + self.w_[0]

    def activation(self, X):
        """ tính kích hoạt """
        z = self.net_input(X)
        return self._sigmoid(z)
    
    def predict_proba(self, X):
        
        return self.activation(X)

    def predict(self, X):
        
        # equivalent to np.where(self.activation(X) >= 0.5, 1, 0)
        return np.where(self.net_input(X) >= 0.0, 1, 0)

In [112]:
import pandas as pd

In [151]:
df = pd.read_csv('/Users/eru/AI.2021/input.csv')
df.head()


sepal_length  sepal_width  petal_length  petal_width     Labeling
0           5.4          3.9           1.7          0.4  Iris-setosa
1           4.6          3.4           1.4          0.3  Iris-setosa
2           5.0          3.4           1.5          0.2  Iris-setosa
3           4.4          2.9           1.4          0.2  Iris-setosa
4           4.9          3.1           1.5          0.1  Iris-setosa

In [152]:
df.shape

(80, 5)

In [153]:
#df = pd.read_csv('/Users/eru/AI.2021/iris.data', header=None)
#df.to_csv('out.csv')
df.head()
df.shape
df.shape[0]

80

In [154]:
import numpy as np
# select setosa and versicolor
y = df.iloc[0:80, 4].values
y = np.where(y == 'Iris-setosa', 1, 0)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [155]:
# extract sepal length and petal length
X = df.iloc[0:80, [0,1,2,3]].values

In [156]:
#X  = df.iloc[0:100,[0,2]].values


In [139]:
# standardize features
X_std = np.copy(X)

#X_std[:,0] = (X[:,0] - X[:,0].mean()) / X[:,0].std()
#X_std[:,1] = (X[:,1] - X[:,1].mean()) / X[:,1].std()

In [140]:
logistR = LogisticRegression(n_iter=500, eta=0.02).fit(X_std, y)
logistR.w_

array([ 0.95929359,  1.5847773 ,  5.49797929, -8.00617532, -3.40316185])

In [157]:
t = pd.read_csv('/Users/eru/AI.2021/output.csv')
XX = t.iloc[0:80,[0,1,2,3]].values
XX

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3]])

In [159]:
yy = logistR.predict(XX)

In [160]:
yy

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])